kind: Deployment
apiVersion: apps/v1
metadata:
  name: robofriends
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robofriends
  template:
    metadata:
      labels:
        app: robofriends
    spec:
      containers:
        - name: robofriends
          image: registry.tr0:31320/robofriends:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always